<a href="https://colab.research.google.com/github/martinpdab/tugasscdl/blob/main/Skenario1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sklearn

In [2]:
import numpy as np
import pandas as pd

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

In [3]:
#memakai dataset
URL = 'https://raw.githubusercontent.com/martinpdab/tugasscdl/main/data%20fix.csv' 
dataframe = pd.read_csv(URL)
dataframe

Period     TE     HU     RF    WS  ...  LAG9  LAG10  LAG11  LAG12  OS
0    Jan-10  26.02  84.74  10.52  0.84  ...     5      2      1      4   0
1    Feb-10  26.32  84.64  12.04  0.86  ...     3      5      2      1   1
2    Mar-10  26.39  85.00   8.65  0.55  ...     3      3      5      2   0
3    Apr-10  26.29  86.17  10.37  0.30  ...     4      3      3      5   0
4    May-10  26.57  85.61   7.35  0.58  ...     1      4      3      3   0
..      ...    ...    ...    ...   ...  ...   ...    ...    ...    ...  ..
103  Aug-18  24.27  76.87   0.00  1.39  ...     1      1      2      3   0
104  Sep-18  25.50  75.73   0.59  1.03  ...     1      1      1      2   1
105  Oct-18  26.58  74.94   0.04  1.39  ...     4      1      1      1   1
106  Nov-18  26.49  82.28  10.53  1.00  ...     1      4      1      1   1
107  Dec-18  26.14  85.45  10.41  0.87  ...     2      1      4      1   1

[108 rows x 21 columns]

In [4]:
# mengambil kolom TE, HU, RF, WS, PD, ABJ, OS dan mengacak dataset
data = dataframe[['TE', 'HU', 'RF', 'WS', 'PD', 'ABJ', 'OS']]
data = shuffle(data)
data.head()

TE     HU     RF    WS      PD     ABJ  OS
59  25.72  88.84  15.66  0.10  825.95  36.490   0
6   25.35  83.52   2.16  1.77  796.41  85.740   0
90  24.46  82.06   7.28  1.52  840.70  88.450   0
0   26.02  84.74  10.52  0.84  792.86  86.960   0
61  25.98  85.71  16.65  0.21  827.01  91.432   0

In [5]:
#train-test split 80-20
train, test = train_test_split(data, test_size=0.2)
print(len(train), 'banyak data train')
print(len(test), 'banyak data test')

#train-test split 70-30
#train, test = train_test_split(data, test_size=0.3)
#print(len(train), 'banyak data train')
#print(len(test), 'banyak data test')

86 banyak data train
22 banyak data test


In [6]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(data, batch_size=32):
  data = data.copy()
  labels = data.pop('OS')
  ds = tf.data.Dataset.from_tensor_slices((dict(data), labels))
  ds = ds.batch(batch_size)
  return ds

In [7]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
test_ds = df_to_dataset(test, batch_size=batch_size)

In [8]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('TE:', feature_batch['TE'])
  print('HU:', feature_batch['HU'])
  print('OS:', label_batch)

Every feature: ['TE', 'HU', 'RF', 'WS', 'PD', 'ABJ']
TE: tf.Tensor([26.43 25.7  26.03 25.14 26.02], shape=(5,), dtype=float64)
HU: tf.Tensor([81.1  82.71 82.13 74.77 84.74], shape=(5,), dtype=float64)
OS: tf.Tensor([0 1 0 0 0], shape=(5,), dtype=int64)


In [9]:
feature_columns = []

for header in ['TE', 'HU', 'RF', 'WS', 'PD', 'ABJ']:
  feature_columns.append(feature_column.numeric_column(header))

In [10]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)
feature_layer

In [28]:
batch_size = 64
train_ds = df_to_dataset(train, batch_size=batch_size)
test_ds = df_to_dataset(test, batch_size=batch_size)

In [29]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(64, activation='relu'),
  layers.Dense(32, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=test_ds,
          epochs=75)

Epoch 1/75
Consider rewriting this model with the Functional API.
Consider rewriting this model with the Functional API.
1/2 [==============>...............] - ETA: 0s - loss: 33.0931 - accuracy: 0.2812WARNING:tensorflow:Layers in a Sequential model should only have a single input tensor, but we receive a <class 'dict'> input: {'TE': <tf.Tensor 'ExpandDims_4:0' shape=(None, 1) dtype=float64>, 'HU': <tf.Tensor 'ExpandDims_1:0' shape=(None, 1) dtype=float64>, 'RF': <tf.Tensor 'ExpandDims_3:0' shape=(None, 1) dtype=float64>, 'WS': <tf.Tensor 'ExpandDims_5:0' shape=(None, 1) dtype=float64>, 'PD': <tf.Tensor 'ExpandDims_2:0' shape=(None, 1) dtype=float64>, 'ABJ': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=float64>}
Consider rewriting this model with the Functional API.
2/2 [==============================] - 1s 164ms/step - loss: 28.2872 - accuracy: 0.2558 - val_loss: 3.5572 - val_accuracy: 0.6818
Epoch 2/75
2/2 [==============================] - 0s 16ms/step - loss: 3.5677 - accuracy: 